#!/usr/bin/env sh

stlHeaders=(
    'algorithm'
    'any'
    'array'
    'atomic'
    'barrier'
    'bit'
    'bitset'
    'charconv'
    'chrono'
    'codecvt'
    'compare'
    'complex'
    'concepts'
    'condition_variable'
    'deque'
    'exception'
    'expected'
    'filesystem'
    'format'
    'forward_list'
    'fstream'
    'functional'
    'future'
    'initializer_list'
    'iomanip'
    'ios'
    'iosfwd'
    'iostream'
    'istream'
    'iterator'
    'latch'
    'limits'
    'list'
    'locale'
    'map'
    'memory'
    'memory_resource'
    'mutex'
    'new'
    'numbers'
    'numeric'
    'optional'
    'ostream'
    'print'
    'queue'
    'random'
    'ranges'
    'ratio'
    'regex'
    'scoped_allocator'
    'semaphore'
    'set'
    'shared_mutex'
    'source_location'
    'span'
    'sstream'
    'stack'
    'stdexcept'
    'stop_token'
    'streambuf'
    'string'
    'string_view'
    'syncstream'
    'system_error'
    'thread'
    'tuple'
    'type_traits'
    'typeindex'
    'typeinfo'
    'unordered_map'
    'unordered_set'
    'utility'
    'valarray'
    'variant'
    'vector'
    'version'
)

for header in "${stlHeaders[@]}"
do
    echo "$header"
    g++ -std=c++23 -fmodules-ts -x c++-system-header "$header"
done

g++ -std=c++23 -fmodules-ts import_all.cpp
