$stlHeaders = @(
    'algorithm',
    'any',
    'array',
    'atomic',
    'barrier',
    'bit',
    'bitset',
    'charconv',
    'chrono',
    'codecvt',
    'compare',
    'complex',
    'concepts',
    'condition_variable',
    'deque',
    'exception',
    'expected',
    'filesystem',
    'format',
    'forward_list',
    'fstream',
    'functional',
    'future',
    'initializer_list',
    'iomanip',
    'ios',
    'iosfwd',
    'iostream',
    'istream',
    'iterator',
    'latch',
    'limits',
    'list',
    'locale',
    'map',
    'memory',
    'memory_resource',
    'mutex',
    'new',
    'numbers',
    'numeric',
    'optional',
    'ostream',
    'print',
    'queue',
    'random',
    'ranges',
    'ratio',
    'regex',
    'scoped_allocator',
    'semaphore',
    'set',
    'shared_mutex',
    'source_location',
    'span',
    'sstream',
    'stack',
    'stdexcept',
    'stop_token',
    'streambuf',
    'string',
    'string_view',
    'syncstream',
    'system_error',
    'thread',
    'tuple',
    'type_traits',
    'typeindex',
    'typeinfo',
    'unordered_map',
    'unordered_set',
    'utility',
    'valarray',
    'variant',
    'vector',
    'version'
)

$extraOptions = @()
$extraObjs = @()

ForEach ($header in $stlHeaders) {
    cl /std:c++latest /nologo /EHsc /exportHeader /headerName:angle /Fo /MP $header
    $extraOptions += '/headerUnit:angle'
    $extraOptions += "$header=$header.ifc"
    $extraObjs += "$header.obj"
}

cl /std:c++latest /nologo /EHsc import_all.cpp @extraOptions @extraObjs
