FROM ubuntu:24.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -qq && \
    apt-get install -y -qq --no-install-recommends \
      g++ linux-tools-common linux-tools-generic \
      heaptrack valgrind time ca-certificates && \
    rm -rf /var/lib/apt/lists/*
WORKDIR /work
